{
    "name": "MGS GYM",
    "version": "1.0",
    "author": "Meisour Global Solutions",
    "description": "GYM MANAGEMENT SYSTEM",
    "category": "Service",
    "depends": [
        "base",
        "sale_management",
        "mail",
        "contacts",
        "account",
    ],
    "license": "GPL-2",
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/gym_branch_rules.xml",
        "data/membership_sequence.xml",
        "data/membership_state.xml",
        "data/cron_jobs.xml",
        "data/equipment_sequence.xml",
        "views/partner_views.xml",
        "views/user_views.xml",
        "views/branch_views.xml",
        "views/shift_views.xml",
        "views/class_views.xml",
        "views/membership_views.xml",
        "views/measurement_views.xml",
        "views/meal_plan_views.xml",
        "views/measurement_report_wizard_views.xml",
        "views/membership_report_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/equipment_views.xml",
        "reports/paper_format.xml",
        "reports/report_actions.xml",
        "reports/membership_report.xml",
        "reports/membership_receipt.xml",
        "reports/measurement_report.xml",
        "views/actions.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mgs_gym/static/lib/chart.umd.min.js",
            "mgs_gym/static/src/js/dashboard.js",
            "mgs_gym/static/src/css/dashboard.css",
            "mgs_gym/static/src/xml/dashboard.xml",
        ]
    },
}  # type: ignore
