{
    "name": "MGS GYM",
    "version": "1.0",
    "author": "Meisour Global Solutions",
    "description": "GYM MANAGEMENT SYSTEM",
    "category": "Service",
    "depends": [
        "base",
        "sale_management",
        "mail",
        "hr",
        "contacts",
        "account",
    ],
    "license": "GPL-2",
    "data": [
        "security/ir.model.access.csv",
        "data/membership_sequence.xml",
        "data/membership_state.xml",
        "data/cron_jobs.xml",
        "views/partner_views.xml",
        "views/branch_views.xml",
        "views/shift_views.xml",
        "views/membership_views.xml",
        "views/measurement_views.xml",
        "views/meal_plan_views.xml",
        "views/actions.xml",
        "views/menus.xml",
    ],
}  # type: ignore
